In [3]:
# load pd

import pandas as pd

df = pd.read_csv("../data/rows_for_db_24-54.csv", sep=";")
df.head()

,file_path,index,sequence_string,sequence_vector
0,data/sequencing_data/barcode24/PAQ63858_pass_b...,0,ATGTTTATGTAACCCTACCTTTCAACTTGGTATTGAATCATTGGGT...,"-0.07501307129859924,0.07857197523117065,0.092..."
1,data/sequencing_data/barcode24/PAQ63858_pass_b...,1,CGTGTTTATGTCTTAACAGGTTATTAAAATGGGTGTTTAACCGCAT...,"-0.019735397771000862,0.012824972160160542,0.0..."
2,data/sequencing_data/barcode24/PAQ63858_pass_b...,2,CTTTCTGGCTTACTGGTTCGTTCTTCAAAACAATATTGGTCATCAT...,"-0.06812695413827896,0.13909874856472015,0.116..."
3,data/sequencing_data/barcode24/PAQ63858_pass_b...,3,TGTGATGCCTTCAACTTTCGGTTGTGCATGAACTGGATTATTGACC...,"-0.051524724811315536,0.11104314029216766,0.12..."
4,data/sequencing_data/barcode24/PAQ63858_pass_b...,4,ATGGCTAACTCGTTCAGTTCTGTGGGCCGGAATATGCTGACCGCAT...,"-0.021049195900559425,0.15970982611179352,0.07..."

In [4]:
df_test = df.copy()

# barcode is informat data/seq/barcode20/passw, get barcode20 and save in diff column
# make it the first in order (barcode)
df_test['barcode'] = df_test['file_path'].str.split('/').str[2]
# order it to be first
df_test = df_test[['barcode', 'file_path', "index", 'sequence_string', 'sequence_vector']]

df_test.head()

,barcode,file_path,index,sequence_string,sequence_vector
0,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,0,ATGTTTATGTAACCCTACCTTTCAACTTGGTATTGAATCATTGGGT...,"-0.07501307129859924,0.07857197523117065,0.092..."
1,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,1,CGTGTTTATGTCTTAACAGGTTATTAAAATGGGTGTTTAACCGCAT...,"-0.019735397771000862,0.012824972160160542,0.0..."
2,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,2,CTTTCTGGCTTACTGGTTCGTTCTTCAAAACAATATTGGTCATCAT...,"-0.06812695413827896,0.13909874856472015,0.116..."
3,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,3,TGTGATGCCTTCAACTTTCGGTTGTGCATGAACTGGATTATTGACC...,"-0.051524724811315536,0.11104314029216766,0.12..."
4,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,4,ATGGCTAACTCGTTCAGTTCTGTGGGCCGGAATATGCTGACCGCAT...,"-0.021049195900559425,0.15970982611179352,0.07..."

In [6]:
# Add a model name column
df_test['model_name'] = 'DNABERT2'
df_test.head()

,barcode,file_path,index,sequence_string,sequence_vector,model_name
0,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,0,ATGTTTATGTAACCCTACCTTTCAACTTGGTATTGAATCATTGGGT...,"-0.07501307129859924,0.07857197523117065,0.092...",DNABERT2
1,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,1,CGTGTTTATGTCTTAACAGGTTATTAAAATGGGTGTTTAACCGCAT...,"-0.019735397771000862,0.012824972160160542,0.0...",DNABERT2
2,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,2,CTTTCTGGCTTACTGGTTCGTTCTTCAAAACAATATTGGTCATCAT...,"-0.06812695413827896,0.13909874856472015,0.116...",DNABERT2
3,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,3,TGTGATGCCTTCAACTTTCGGTTGTGCATGAACTGGATTATTGACC...,"-0.051524724811315536,0.11104314029216766,0.12...",DNABERT2
4,barcode24,data/sequencing_data/barcode24/PAQ63858_pass_b...,4,ATGGCTAACTCGTTCAGTTCTGTGGGCCGGAATATGCTGACCGCAT...,"-0.021049195900559425,0.15970982611179352,0.07...",DNABERT2

In [ ]:
#df_test.to_csv("data/rows_for_db_20,22-23.csv", sep=";", index=False)

In [10]:
import pandas as pd

df = pd.read_csv("../data/rows_for_db_final_20,22-23.csv", sep=";")
df.head()

,barcode,file_path,index,sequence_string,sequence_vector
0,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,1,ATGTTCCTGTGCTTGGTTGGGTTGTAAAAACCGGGTGTTTAACCTT...,"-0.054356034845113754,0.11163334548473358,0.12..."
1,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,0,GTTTATGTTAACCTGACCGTTATCAACCGGGTGTTTAACCTCGCGT...,"-0.06506913900375366,0.09258261322975159,0.059..."
2,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,2,TATGTCCTGTTACTTCGTTCAGTTATATGCCAGCCATGCCATGCGA...,"-0.11293024569749832,0.14618229866027832,0.003..."
3,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,3,GTTATGTAACGTACTTCGTTCAGTTCTATGCAGCCGATATTAACCT...,"-0.06913761794567108,0.14707019925117493,0.120..."
4,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,4,TATGTCCTGTTACTGGTTCATGCAGCCATATAACCTCATTGTCCTG...,"-0.05785530060529709,0.12198787927627563,0.118..."

In [9]:
df_final = pd.read_csv("rows_for_db_final.csv", sep=";")
df_final.head()

,barcode,file_path,index,sequence_string,sequence_vector
0,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,1,ATGTTCCTGTGCTTGGTTGGGTTGTAAAAACCGGGTGTTTAACCTT...,"-0.054356034845113754,0.11163334548473358,0.12..."
1,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,0,GTTTATGTTAACCTGACCGTTATCAACCGGGTGTTTAACCTCGCGT...,"-0.06506913900375366,0.09258261322975159,0.059..."
2,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,2,TATGTCCTGTTACTTCGTTCAGTTATATGCCAGCCATGCCATGCGA...,"-0.11293024569749832,0.14618229866027832,0.003..."
3,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,3,GTTATGTAACGTACTTCGTTCAGTTCTATGCAGCCGATATTAACCT...,"-0.06913761794567108,0.14707019925117493,0.120..."
4,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,4,TATGTCCTGTTACTGGTTCATGCAGCCATATAACCTCATTGTCCTG...,"-0.05785530060529709,0.12198787927627563,0.118..."

In [13]:
df.head()

,barcode,file_path,index,sequence_string,sequence_vector
0,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,1,ATGTTCCTGTGCTTGGTTGGGTTGTAAAAACCGGGTGTTTAACCTT...,"-0.054356034845113754,0.11163334548473358,0.12..."
1,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,0,GTTTATGTTAACCTGACCGTTATCAACCGGGTGTTTAACCTCGCGT...,"-0.06506913900375366,0.09258261322975159,0.059..."
2,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,2,TATGTCCTGTTACTTCGTTCAGTTATATGCCAGCCATGCCATGCGA...,"-0.11293024569749832,0.14618229866027832,0.003..."
3,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,3,GTTATGTAACGTACTTCGTTCAGTTCTATGCAGCCGATATTAACCT...,"-0.06913761794567108,0.14707019925117493,0.120..."
4,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,4,TATGTCCTGTTACTGGTTCATGCAGCCATATAACCTCATTGTCCTG...,"-0.05785530060529709,0.12198787927627563,0.118..."

In [15]:
# append df to df_final
_df_final = pd.concat([df, df_test], ignore_index=True)
assert len(_df_final) == len(df_test) + len(df)

In [17]:
_df_final["model_name"] = "DNABERT2"
_df_final.head()

,barcode,file_path,index,sequence_string,sequence_vector,model_name
0,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,1,ATGTTCCTGTGCTTGGTTGGGTTGTAAAAACCGGGTGTTTAACCTT...,"-0.054356034845113754,0.11163334548473358,0.12...",DNABERT2
1,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,0,GTTTATGTTAACCTGACCGTTATCAACCGGGTGTTTAACCTCGCGT...,"-0.06506913900375366,0.09258261322975159,0.059...",DNABERT2
2,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,2,TATGTCCTGTTACTTCGTTCAGTTATATGCCAGCCATGCCATGCGA...,"-0.11293024569749832,0.14618229866027832,0.003...",DNABERT2
3,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,3,GTTATGTAACGTACTTCGTTCAGTTCTATGCAGCCGATATTAACCT...,"-0.06913761794567108,0.14707019925117493,0.120...",DNABERT2
4,barcode20,data/sequencing_data/barcode20/PAQ63858_pass_b...,4,TATGTCCTGTTACTGGTTCATGCAGCCATATAACCTCATTGTCCTG...,"-0.05785530060529709,0.12198787927627563,0.118...",DNABERT2

In [ ]:
df_test.to_csv("../data/rows_for_db_final_20,22-54.csv", sep=";", index=False)